### PR TITLE
Tidyups

### PR DESCRIPTION
**Pull request by jnewbery**
a few tidy ups

### CODE REVIEW

**Comment by jnewbery** [comment]
ping @jonasschnelli

**Comment by jnewbery** [comment]
ping @jonasschnelli

**Comment by jnewbery** [comment]
I plan to merge this on Friday unless there's any objection.

**Comment by jonasschnelli** [comment]
Thanks @jnewbery!
Ping me on IRC if I should deploy git to the webserver. Sadly there is currently no git auto-deploy.

**Pull request merged**
